# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
