# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180211_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
